# Key Scientific Libraries

Python has a vast number of useful scientific libraries. 

## Numpy

Numpy is the base for much of the scientific computing landscape in Python.

Unlike R or Matlab, Python was not originally built to support heavy numerical computing, however, this changed early on in its development and work on Numpy's predecessors started in the mid 1990s. Numpy in its current state is over 12 years old.

Under the hood it employs various C/ Fortran bindings similar to Matlab.

### Arrays

Numpy arrays are like normal Python lists but with lots of useful functions added on

In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])

In [2]:
# Maximum
a.max()

7

In [3]:
# Sum
a.sum()

28

In [4]:
# Product
a.prod()

5040

In [5]:
# Mean
a.mean()

4.0

In [6]:
# Standard deviation
a.std()

2.0

### Matrices

In [7]:
import numpy as np

m = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

m.shape

(3, 3)

Indexing looks fairly similar to normal list indexing. To access a specific element we specify the row and column index:

In [8]:
# Element in 2nd row (index 1) and 3rd column (index 2)
m[1, 2]

6

To index a whole row or column we use a colon `:`

In [9]:
# Second row (index 1)
m[1, :]

array([4, 5, 6])

In [10]:
# Third column (index 2)
m[:, 2]

array([3, 6, 9])

Matrix multiplication is fairly straightfoward method calls too:

In [14]:
# Dot product
m.dot([10, 11, 12])

array([ 68, 167, 266])

## Scipy

## Matplotlib


## Pandas

## Scikit Learn


## Tensorflow
