In [1]:
%matplotlib

import numpy as np
import matplotlib.pyplot as plt

Using matplotlib backend: TkAgg


# Key Scientific Libraries

Python has a vast number of useful scientific libraries. So, the key message:

**Before writing your own scientific functions, check someone hasn't already done it in the following pacakges!**

These packages have been worked on by large numbers of professional programmers who will have optimised and tested them extensively.

For much more detail and more exercises you can check out http://www.scipy-lectures.org/intro/

## Numpy

Numpy is the result of over 20 years of development and forms the base of scientific computing in Python. It's the engine that handles arrays, matrices, polymnomials etc.

Under the hood it employs various C/ Fortran bindings similar to Matlab and R.

### Arrays

Numpy arrays are like normal Python lists but with lots of useful functions added on

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [3]:
# Maximum
a.max()

7

In [4]:
# Sum
a.sum()

28

In [5]:
# Product
a.prod()

5040

In [6]:
# Mean
a.mean()

4.0

In [7]:
# Standard deviation
a.std()

2.0

### Matrices

In [8]:
m = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

m.shape

(3, 3)

Indexing looks fairly similar to normal list indexing. To access a specific element we specify the row and column index:

In [9]:
# Element in 2nd row (index 1) and 3rd column (index 2)
m[1, 2]

6

To index a whole row or column we use a colon `:`

In [10]:
# Second row (index 1)
m[1, :]

array([4, 5, 6])

In [11]:
# Third column (index 2)
m[:, 2]

array([3, 6, 9])

Matrix multiplication is fairly straightfoward method calls too:

In [12]:
# Dot product
m.dot([10, 11, 12])

array([ 68, 167, 266])

## Matplotlib

`matplotlib` is the most popular Python library for producing graphs. The `mat` part of the title indicates the similarities with the Matlab plotting interface.


First we can produce some data to plot. We can start with a simple sine and cosine:

In [13]:
x_data = np.linspace(-np.pi, np.pi, 256)
cos_data = np.cos(x_data)
sin_data = np.sin(x_data)

Now using `matplotlib` we can plot both on the same axes. Note, to start an interactive plotting session you can add `%matplotlib` in your Jupyter notebook.

In [14]:
plt.plot(x_data, cos_data)
plt.plot(x_data, sin_data)

plt.show()

### Spines

To move the spines (lines that mark the edges/ axes) we can do the following.

Note the use of `plt.gca()` to get the current axes. This is useful when you're handling lots of subplots.

To move the x-axis (i.e. the bottom spine), we can do:

In [15]:
ax = plt.gca()
ax.spines['bottom'].set_position(('data', 0))

Now to remove the lines at the top and side:

In [16]:
ax.spines['top'].set_color('none')
ax.spines['right'].set_color('none')

### Grids

To add a grid to our plot:

In [17]:
ax.grid(color='tab:gray', linestyle='--', linewidth=0.5, alpha=0.5)

### Subplots

Matplotlib uses a similar grid system to Matlab. A good set of examples can be seen [here](http://www.scipy-lectures.org/intro/matplotlib/index.html#subplots).

To set up a 2x2 grid and start working on the cell in the top left we can run the following:

In [18]:
plt.figure()

plt.subplot(2, 2, 1)

Now to plot in this subplot we can call the normal plotting commands, e.g.

In [19]:
plt.plot(x_data, cos_data)
plt.plot(x_data, sin_data)

To get the second plot we can run:

In [20]:
plt.subplot(2, 2, 2)

And plot in there as normal:

In [21]:
plt.plot(x_data, np.power(x_data, 2))
plt.plot(x_data, np.power(x_data, 3))

## Exercise - 2D Heatmap

Plot a 2D heatmap of some random numbers. To do this you can use the `numpy.random.rand` method which works like this:

```
# Generate a random 30x30 matrix
random_matrix = np.random.rand(30, 30)
```

You can plot a 2D representation of a matrix like this:

```
plt.pcolor(random_matrix)
```

Finally, you can call `plt.show()` to display your plot.

You can change the colour of your plot by mofidying the `cmap` property when calling `pcolor`, for example:

```
plt.pcolor(random_matrix, cmap=plt.cm.hot)
```

Or 

```
plt.pcolor(random_matrix, cmap=plt.cm.Greens)
```

Finally you can add a colour bar by calling `plt.colorbar()`.

In [22]:
# Create a new figure
plt.figure()

# Put your code here:

## Exercise  - Subplots

Create a 2x2 grid of subplots, plotting `y = sin(x)`, `y=cos(x)`, `y=arcsin(x)` and `y=arccos(x)`.

To generate a linear array of x values you can use the `np.linspace` function, e.g.:

```
# Create 50 values between zero and ten
x_data = np.linspace(0, 10, 50)
```

You can then use the `np.sin`, `np.cos`, `np.arcsin` and `np.arccos` functions on the array to generate the y values, e.g.

```
y_data = np.sin(x_data)
```

Try adding titles to each plot by calling `plt.title('your title here')` at the right points.

Does the layout look funny? Try adding a call to `plt.tight_layout()` to fix it.

In [23]:
# Create a new figure
plt.figure()

# Put your code here

## Scipy

`scipy` is a collection of domain-specific scientific computing tools. 

It supports things like interpolation, integration, optimization, image processing, statistics, special functions and so on. It is tightly integrated with `numpy`.

It's worth browsing over some of the packages on offer to get a feel for what's there:

- [Stats](https://docs.scipy.org/doc/scipy/reference/stats.html)
- [Interpolation](https://docs.scipy.org/doc/scipy/reference/interpolate.html)
- [Linear algebra](https://docs.scipy.org/doc/scipy/reference/linalg.html)
- [Fourier transforms](https://docs.scipy.org/doc/scipy/reference/fftpack.html)
- [Integration and ODEs](https://docs.scipy.org/doc/scipy/reference/integrate.html)
- [Image processing](https://docs.scipy.org/doc/scipy/reference/ndimage.html)
- [Optimisation and root finding](https://docs.scipy.org/doc/scipy/reference/optimize.html)
- [Signal processing](https://docs.scipy.org/doc/scipy/reference/signal.html)
- [Sparse matrices](https://docs.scipy.org/doc/scipy/reference/sparse.html)